#!/bin/bash

qemu-system-arm -cpu cortex-m4 -machine netduinoplus2 -nographic -semihosting-config enable=on,target=native -d in_asm,cpu,exec,int -kernel ../target/thumbv7em-none-eabihf/debug/krust -S -gdb tcp::3333